# Generated by Django 4.1.7 on 2023-03-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zomato', '0002_rename_fullname_account_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='date_of_birth',
            new_name='dob',
        ),
    ]
