# Generated by Django 4.1.7 on 2023-03-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomato', '0003_rename_date_of_birth_account_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
    ]
